networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    image: nginx
    env_file: .env
    build: requirements/ngnix/
    restart: always
    user: root
    # volumes:
    ports:
      - "443:443"
    depends_on:
      - wp
    networks: 
      - inception
    container_name: nginx
  
  db:
    image: mariadb
    env_file: .env
    build: requirements/mariadb
    restart: always
    user: root
    # volumes:
    networks:
      - inception
    container_name: mariadb
  
  wp:
    image: wordpress
    env_file: .env
    depends_on: 
      - db
    # volumes:
    restart: always
    build: /requirements/wordpress/
    user: root
    networks:
      - inception
    container_name: wordpress

