# Docker Compose is a tool for running multi-container applications on Docker defined using the Compose file format
# The Compose file is a YAML file defining services, networks, and volumes for a Docker application

# By default Compose sets up a single network for your app. Each container for a service joins 
# the default network and is both reachable by other containers on that network, and discoverable 
# by them at a hostname identical to the container name.
version: "3.5"

# change the settings of the app-wide default network by defining an entry under networks named default
networks:
  inception:
    driver: bridge
# bridge is the default network driver
# bridge networks are usually used when your applications run in standalone containers that need to communicate

# Когда Docker создает тома, содержимое тома сохраняется в директории файловой системы хоста, 
# /var/lib/docker/volumes/, а данным процессом управляет Docker.
volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /Users/sexysushi/mariadb 
# path to a mounting point must exist before building containers

  # wordpress:
  #   driver: local
  #   name: wordpress
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/${USER}/data/wordpress

services:
  mariadb:
    build: ./requirements/mariadb/
    env_file: .env
    # image: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    ports:
      - 3306:3306

  # wordpress:
  #   build: ./requirements/wordpress/
  #   env_file: .env
  #   container_name: wordpress
  #   image: wordpress
  #   restart: unless-stopped
  #   volumes: 
  #     - wordpress:/var/www/html
  #   networks: 
  #     - inception
  #   depends_on:
  #     - mariadb

  # nginx:
  #   build: ./requirements/nginx/
  #   env_file: .env
  #   container_name: nginx
  #   image: nginx
  #   restart:  unless-stopped
  #   volumes:
  #     - wp:/var/www/html
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - inception
  #   ports:
  #     - 443:443 # https
