version: "3.7"

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    image: mariadb
    env_file: .env
    build: requirements/mariadb
    user: root
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - inception
    container_name: mariadb
    restart: always
  # nginx:
  #   image: nginx
  #   env_file: .env
  #   build: requirements/ngnix/
  #   restart: always
  #   user: root
  #   # volumes:
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - wp
  #   networks: 
  #     - inception
  #   container_name: nginx
  
  # wp:
  #   image: wordpress
  #   env_file: .env
  #   depends_on: 
  #     - db
  #   # volumes:
  #   restart: always
  #   build: /requirements/wordpress/
  #   user: root
  #   networks:
  #     - inception
  #   container_name: wordpress

